site_name: My Docs
site_url: https://prosperousheart.github.io/mkdocs-jupyterlite-template-repo/
repo_url: https://github.com/prosperousheart/mkdocs-jupyterlite-template-repo/

nav:
  - Home: index.md
  - Notebook In Root: notebook.ipynb
  - Directory:
      - Notebook In Directory: tmp-ex-dir/notebook.ipynb

extra_css:
  - extra.css

plugins:
  - jupyterlite:
      enabled: true
      notebook_patterns:
        - '*.ipynb'
