[project]
name = "mkdocs-jupyterlite-template-repo"
version = "0.1.0"
description = "Repo template for MkDocs with JupyterLite integration as use for PyTexas 2026 talk bonus."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-jupyterlite>=0.4.1",
]
